#!/bin/bash
# Author: Doan Bui (bxdoan93@gmail.com)
# htttps://github.com/bxdoan/

### ----------------------------------------------------------------------------
### Check  ~/.ssh/ folder and generate ssh key
### ----------------------------------------------------------------------------
if [ ! -f /home/$USER/.ssh/id_rsa ]; then
    printf "File id_rsa not found!\nGenerating ssh key...\n"
    ssh-keygen -f /home/$USER/.ssh/id_rsa -t rsa -N '' -b 4096 -C "bxdoan93@gmail.com"
    echo "Generate id_rsa complete"
fi
echo "File id_rsa is ready"

### ----------------------------------------------------------------------------
### Check and create config file in ssh
### ----------------------------------------------------------------------------
if [ ! -f /home/$USER/.ssh/config ]; then
    printf "File config not found!\nCreating $USER/.ssh/config...\n"
    echo "StrictHostKeyChecking no" > /home/$USER/.ssh/config
    echo "Generate /home/$USER/.ssh/config complete"
else
    cat /home/$USER/.ssh/config | grep "StrictHostKeyChecking"
    if [ $? -ne 0 ]; then
        echo "StrictHostKeyChecking no" >> /home/$USER/.ssh/config
    fi
fi

### ----------------------------------------------------------------------------
### add ssh key into github
### ----------------------------------------------------------------------------
die() {
    echo "$@" >&2
    exit 1
}
user="bxdoan"
title="$(hostname)"
path="${path:-$HOME/.ssh/id_rsa.pub}"

# check if the path is available
if [ ! -f $path ]; then
    die "$path: no such file or directory"
fi
key_data="$(cat "$path")"

ssh -T git@github.com 2>&1 | grep "success"
if [ $? -ne 0 ]; then
    result="$(curl -u "$user" \
            --data "{\"title\":\"$title\",\"key\":\"$key_data\"}" \
            https://api.github.com/user/keys
         )"
fi

ssh -T git@github.com 2>&1 | grep "success"
if [ $? -ne 0 ]; then
    die "sorry, can NOT connect github"
fi

### ----------------------------------------------------------------------------
### Clone source
### ----------------------------------------------------------------------------
setupconfig () {
    if [ ! -f ~/.gitconfig ]; then
        cp ~/Repo/config/GIT/.gitconfig ~/
        echo "~/.gitconfig done"
    fi

    if [ ! -f /home/$USER/.bashrc ]; then
        echo "~/.bashrc is NOT exist, creating..."
        cp ~/Repo/config/BASH/.bashrc ~/
    else
        echo "~/.bashrc is exist, appending..."
        cat ~/.bashrc | grep "upd_bash"
        if [ $? -ne 0 ]; then
            cat ~/Repo/config/BASH/.bashrc >> ~/.bashrc
        fi
    fi
    echo "~/.bashrc done"

    if [ ! -f ~/.emacs ]; then
        cp ~/Repo/config/EMACS/.emacs ~/
        echo "~/.emacs done"
    fi

    if [ ! -d ~/.emacs.d ]; then
        cp -r ~/Repo/config/EMACS/.emacs.d/ ~/
        echo "~/.emacs.d/ done"
    fi
}

if [ ! -d /home/$USER/Repo ]; then
    mkdir /home/$USER/Repo
    echo "Create ~/Repo"
fi

if [ ! -d ~/Repo/config ]; then
    config="$(git clone git@github.com:bxdoan/config.git ~/Repo/config/)"
    if [ $? -ne 0 ]; then
        die "Can NOT clone config repository"
    fi
    local r = "$(setupconfig)"
fi

if [ ! -d ~/Repo/source ]; then
    source="$(git clone git@github.com:bxdoan/source.git ~/Repo/source/)"
    if [ $? -ne 0 ]; then
        die "Can NOT clone source repository"
    fi
fi

### ----------------------------------------------------------------------------
### setup
### ----------------------------------------------------------------------------

source ~/.bashrc
echo "Set up done! Ready to work"
